<?xml version="1.0" encoding="utf-8"?><Database Name="YouKeMei" Class="YouKeMeiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.0.3;Initial Catalog=YouKeMei;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="YouKeMeiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_Article" Member="tb_Article">
    <Type Name="tb_Article">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InfoSummary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="InfoContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PublishTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InfoType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PictureURL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AttachmentURL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ArticleType" Member="tb_ArticleType">
    <Type Name="tb_ArticleType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArticleType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>